<?php
/**
 * Created by PhpStorm.
 * User: York
 * Date: 26.09.2017
 * Time: 15:33
 */

namespace justyork\yii2_multilanguage\behaviors;

use common\models\Language;
use dosamigos\tinymce\TinyMce;
use Yii;
use yii\base\Behavior;
use yii\db\ActiveRecord;
use yii\helpers\Html;

class CMSLanguage extends Behavior{

    public $fields;

    public $_local_attributes = [];

    private $translate_model;
    private $lang;

    public function init(){
        if(!Yii::$app->request->lang) $this->lang = Yii::$app->sourceLanguage;
        else $this->lang = Yii::$app->request->lang;
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function events()
    {
        return [
            ActiveRecord::EVENT_INIT => 'onInit',
            ActiveRecord::EVENT_AFTER_FIND => 'afterFind',
            ActiveRecord::EVENT_AFTER_UPDATE => 'afterSave',
            ActiveRecord::EVENT_AFTER_INSERT => 'afterSave',
            ActiveRecord::EVENT_BEFORE_DELETE => 'beforeDelete',
        ];
    }


    /**
     * Get attribute
     *
     * @param $name
     * @return bool|mixed
     */
    public function localAttributes($name){
        if(!isset($this->_local_attributes[$name]))
            return false;

        return $this->_local_attributes[$name];
    }

    /**
     * Инициализация
     */
    public function onInit(){
        $this->LoadOptions();
        $this->translate_model = 'common\models\translate\\'.$this->owner->formName().'Translate';
    }


    /**
     * After find model
     */
    public function afterFind()
    {
        $this->LoadTranslates();
    }


    /**
     * Сохранить мультиязычные переменные в базу
     *
     */
    public function afterSave(){

        $data = Yii::$app->request->post($this->owner->formName());

        if($data){
            foreach (Language::map() as $lng){
                foreach ($this->fields as $field){
                    $this->_local_attributes[$field.'_'.$lng] = $data[$field.'_'.$lng];
                }
            }
        }

        $class = $this->translate_model;

        foreach (Language::map() as $lng){
            $model = $class::find()
                ->where(
                    ['parent_id' => $this->owner->id,
                        'language' => $lng])
                ->one();

            if(!$model){
                $model = new $class;
                $model->parent_id = $this->owner->id;
                $model->language = $lng;
            }

            foreach ($this->fields as $field){

                $model->$field = $this->_local_attributes[$field.'_'.$lng];
            }
            $model->save();
        }
    }


    /**
     * Удалить переводы
     */
    public function beforeDelete(){

        $model = $this->translate_model;
        $model::deleteAll('parent_id = :id', ['id' => $this->owner->id]);
    }



    /**
     * Получить связанные поля с переводами
     *
     * @return \yii\db\ActiveQuery
     */
    public function get_translate(){
        $model = $this->translate_model;
        return $this->owner->hasMany($model, ['parent_id' => 'id']);
    }

    /**
     * Загрузить изначальные настройки мультиязычности
     */
    private function LoadOptions(){
        foreach ($this->fields as $field){
            $this->_local_attributes[$field] = '';

            foreach (Language::map() as $lng){
                $this->_local_attributes[$field.'_'.$lng] = '';
            }
        }
    }

    /**
     * Загрузить переводы полей
     */
    private function LoadTranslates(){
        $translates = $this->owner->_translate;

        foreach ($translates as $translate){
            foreach ($this->fields as $field){
                if($this->lang == $translate->language)
                    $this->_local_attributes[$field] = $translate->$field == null ? '' : $translate->$field;

                $this->_local_attributes[$field.'_'.$translate->language] = $translate->$field == null ? '' : $translate->$field;
            }
        }
    }


    public function LangField($form, $field, $lng, $attr){
        $fld = $field.'_'.$lng->code;

        if($attr['multiple'])
            $fld .= '[]';

        $model_field = $form->field($this->owner, $fld);
        switch ($attr['type']){
            case "editor":
                return $model_field->widget(TinyMce::className(), [
                    'clientOptions' => [
                        'plugins' => [
                            "advlist autolink lists link charmap print preview anchor",
                            "searchreplace visualblocks code fullscreen",
                            "insertdatetime media table contextmenu paste"
                        ],
                        'toolbar' => "undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
                    ]
                ]);
                break;
            case "textarea":
                return $model_field->textarea();
                break;
            case "textInput":
                return $model_field->textInput();
                break;

        }

    }
}